-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 23:28:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema readrater
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema readrater
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `readrater` DEFAULT CHARACTER SET utf8 ;
USE `readrater` ;

-- -----------------------------------------------------
-- Table `readrater`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readrater`.`editora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cnpj` VARCHAR(19) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readrater`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readrater`.`livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `sinopse` TEXT NOT NULL,
  `numeroPaginas` INT NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `dataPublicacao` DATE NOT NULL,
  `editora_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_livro_editora_idx` (`editora_id` ASC) VISIBLE,
  CONSTRAINT `fk_livro_editora`
    FOREIGN KEY (`editora_id`)
    REFERENCES `readrater`.`editora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readrater`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readrater`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readrater`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readrater`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `usuario` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senhal` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readrater`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readrater`.`autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `biografia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readrater`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readrater`.`avaliacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nota` INT NOT NULL,
  `dataAvaliacao` DATE NOT NULL,
  `comentario` TEXT NOT NULL,
  `usuario_id` INT NOT NULL,
  `livro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_review_livro1_idx` (`livro_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `readrater`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_livro1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `readrater`.`livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readrater`.`livro_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readrater`.`livro_genero` (
  `genero_id` INT NOT NULL,
  `livro_id` INT NOT NULL,
  INDEX `fk_genero_has_livro_livro1_idx` (`livro_id` ASC) VISIBLE,
  INDEX `fk_genero_has_livro_genero1_idx` (`genero_id` ASC) VISIBLE,
  CONSTRAINT `fk_genero_has_livro_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `readrater`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genero_has_livro_livro1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `readrater`.`livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readrater`.`autor_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readrater`.`autor_genero` (
  `genero_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  INDEX `fk_genero_has_autor_autor1_idx` (`autor_id` ASC) VISIBLE,
  INDEX `fk_genero_has_autor_genero1_idx` (`genero_id` ASC) VISIBLE,
  CONSTRAINT `fk_genero_has_autor_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `readrater`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genero_has_autor_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `readrater`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readrater`.`autor_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readrater`.`autor_livro` (
  `livro_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  INDEX `fk_livro_has_autor_autor1_idx` (`autor_id` ASC) VISIBLE,
  INDEX `fk_livro_has_autor_livro1_idx` (`livro_id` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_autor_livro1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `readrater`.`livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_autor_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `readrater`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
